export const PRODUCT_LIST_REQUEST = 'RODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'RODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'RODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'RODUCT_LIST_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'RODUCT_LIST_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'RODUCT_LIST_FAIL'